name: dartvn
author: Alex Gann
version: 0.0.0
description: Visual Novel engine
dependencies:
  browser: any
  stagexl: '>=0.9.0 <0.10.0'
  stagexl_richtextfield:
    git: https://github.com/realbluesky/StageXL_RichTextField.git
    version: '>=0.1.1'
  yaml: 0.9.0
