name: dartvn
version: 0.0.0
author: Alex Gann
description: Visual Novel engine
dependencies:
  browser: any
  stagexl:
    git: https://github.com/bp74/StageXL.git
  stagexl_richtextfield:
    git: https://github.com/realbluesky/StageXL_RichTextField.git
  yaml: any
